services:
  mongodb:
    container_name: opass_mongodb
    image: mongodb/mongodb-community-server:4.4.8-ubuntu2004
    # AVX issue
    # https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
    restart: always
    ports:
      - 27017:27017
    command: mongod --dbpath /tmp
    networks:
      - ccip-server_default

  # https://hub.docker.com/_/mongo-express
  mongo-express:
    container_name: opass_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ../.env
    depends_on:
      - mongodb
